name: lowercaseFolderName

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lowercase_folder_name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check folder names are lowercase
        run: bash ./scripts/folder_name_test.sh
